### ISSUE TITLE
Setting Babel configuration

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs-transform-babel#2]
We have a few options for setting Babel configuration. Currently SystemJS 2.0 itself is configurationless so it would be good to set a good precedent here.

Previously we had `System.babelOptions` and `System.config({ babelOptions: ... })`.

Perhaps we should stick with `System.babelOptions` as an object?

Feedback welcome.

**Comment by rcklmk** [comment]
With focus on "... the principle of a focused hackable core with a minimal footprint.", is SystemJS 2.0 configurationless by the design? Sorry for having a similar question as the one I had at disqus but just trying to understand the goals and current roadmap.

If that's so maybe having a separate explicit sink for handling plugin configurations can help the core module stay clean and minimal like so:

```
System.plugins({
  'babel-transform': {
    ...
  }

  // or

  'babelOptions': {
    ...
  }

})
```
---
`System.babelOptions` looks somewhat undesirable as it feels like exposing an internal implementation to API consumers so personally I prefer `System.config({ babelOptions: ... })` if the one above doesn't work. Having everything under `.config` can be confusing, though, as it's not clear whether the configuration is for the core module or for the plugins.

**Comment by guybedford** [comment]
> With focus on "... the principle of a focused hackable core with a minimal footprint.", is SystemJS 2.0 configurationless by the design? Sorry for having a similar question as the one I had at disqus but just trying to understand the goals and current roadmap.

At the moment, yes, partly because configuration isn't needed in core by following the latest specs. But yes this feature is the first that places configuration pressure on the project. We could provide a dedicated plugin configuration solution that can be extended and used by any other plugins certainly, like you are suggesting.

The worry with a `System.config` is just making the extension paradigm sensible.

Perhaps something like:

```js
System.config({
  [configname: string]: any
});
```

System.getConfig(configname: string); // returns the configuration

The next questions are:
* Does extension apply by default
* Can any configuration property be set or must configuration be first "declared"
* Does validation apply? Or where do extensions hook configuration validation?

We could try and tackle such things in a generic configuration extension but it all gets quite complex.

So that's why I was tending towards a `System.babelOptions = ...` sort of thing that can just be copied by other extensions as a pattern.

Alternatively perhaps `System.configureBabel(babelConfig)` as the pattern or some functional pattern like that?
```

**Comment by thiscantbeserious** [comment]
> So that's why I was tending towards a `System.babelOptions = ...` sort of thing that can just be copied by other extensions as a pattern.
> 
> Alternatively perhaps `System.configureBabel(babelConfig)` as the pattern or some functional pattern like that?

Speaking from experience - this looks like a bad idea similar to how Require did it back in the days.

Write randomly (?) named subobjects to the global object and introduce an configuration hell where nobody knows where to look at finally anymore (oh how lovely to debug). 

How would you get an idea which plugins are successfully loaded at runtime and what configurations they supply? 

Say you have 20 Plugins (sounds like a mess, yes just giving an extreme example) - they're randomly split across the System object that you have to dig out manually (even if you enforce f.e. a namespace, that doesn't look like a good idea).

I'd enforce that Plugins have to register themself with a unique ID, which then uses aboves System.plugin scope to provide their configuration via their registered ID. You could theoretically also use that to write information back to the configuration object (e.g. loaded = true)

That way you can modularize even the core configuration via Plugins and keep a separation of concerns in a structured order. It also avoids the System.config mess - win/win. No?

----

Speaking about Plugins - I'll likely have to write a plugin-text and a plugin-i18n/json for the new SystemJS v4 base since we're moving our Framework from AMD+RequireJS to Rollup+SystemJS ... and we're currently using Require to load templates and translations dynamically.

How would I move forward the best for providing upstream support? PR for the existing plugins? 

The lifetime of this project is likely going to be 5-10 years and above, so I'd like to optimally keep a close focus to the way SystemJS intents to move forward to minimize breaking changes accross major revisions in the best way possible (yikes, I'm not to delussional to think that won't happen given the current state of things tought).

**Comment by viT-1** [comment]
@thiscantbeserious 
> Speaking about Plugins - I'll likely have to write a plugin-text

Excuse me, can you share an example with SystemJS >2.0 and plugin-text for html-template?
